site_name: Minewind Wiki
site_url: https://21943second.github.io/MinewindWiki/
repo_url: https://github.com/21943second/MinewindWiki
theme:
  name: material
  icon:
    logo: fontawesome/solid/wind
  favicon: assets/wind-solid-full.svg
  features:
    - navigation.footer
    - content.footnote.tooltips
  palette: 
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: deep purple
      accent: green
  
    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Light mode
      primary: deep purple
      accent: green

# Choose what shows up in global navigation
#nav:
#  - Home: index.md
#  - User Guide:
#    - Writing your docs: writing-your-docs.md
#    - Styling your docs: styling-your-docs.md
#  - About:
#    - License: license.md
#    - Release Notes: release-notes.md

markdown_extensions:
  - attr_list
  # Support for emojis, which can be searched through at the link below
  # https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#search
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  # Support for tabs (and custom diagrams)
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  # Support for 'callouts'
  - admonition
  - pymdownx.details
  # Better image functionality
  - md_in_html
  - pymdownx.blocks.caption
  # Footnote support
  - footnotes

plugins:
  - tags
  - search
  - alias
  - site-urls
  - glightbox
  - macros:
      include_dir: include
      module_name: include/source_code/read_json
  - autorefs:
      resolve_closest: true

extra:
  social:
    - icon: simple/discord
      link: https://discord.gg/DepcKjZQnp